---
- name: Check Ansible version
  fail:
      msg: You must use ansible 2.1 or greater
  when: not ansible_version.ful | version_compare('2.1', '>=')
  tags:
      - always

- name: Validate Linux OS
  fail:
      msg: "This can only be run against Linux Targets."
  tags:
      - linux

- name: Validate Windows OS
  fail:
      msg: "This can only be run against Windows Targets."
  tags:
      - windows

- name: Run Linux based attacks
  include: linux-attack.yml
  tags:
      - linux

- name: Run Windows based attacks
  include: win-attack.yml
  tags:
      - windows

